- name: Creates directory
  file:
    path: ~/backend-app
    state: directory

- name: extract backend files
  unarchive:
    src: "files/artifact.tar.gz"
    dest: "~/backend-app"

- name: "Installing backend Node Dependencies"
  shell: |
    cd ~/backend-app
    npm install

- name: "Executing backend app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service so that if EC2 is restarted for any reason then application will start on EC2 start up automatically"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save